// import { userModel } from "@/entities/user";

// // const roboto = Roboto({
// //   weight: ["400", "500"],
// //   subsets: ["latin"],
// //   display: "swap",
// // });

//
// import { routesModel } from "@/entities/routes";

// export const metadata: Metadata = {
//   title: "TILD - Your Time Manager",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className={roboto.className}>
//       <body>
//         <routesModel.RouteProvider>
//           <userModel.AuthProvider>{children}</userModel.AuthProvider>
//         </routesModel.RouteProvider>
//       </body>
//     </html>
//   );
// }
